/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://wyrmmzvjlncyhoh2sm2bptlnra.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oovvuffl35bhhn3yifvlgdfcdy",
    "aws_cognito_identity_pool_id": "us-east-2:6d1996b8-79cd-4ece-ba01-98d04bcfffb4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_A5YM5ebUS",
    "aws_user_pools_web_client_id": "67j1h7q15ugldt2mtg9c2dkb3b",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
